version: '3.8'

services:
  api:
    build: .
    container_name: miles-tunes-api
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    volumes:
      - ./downloads_data:/app/downloads